### ISSUE TITLE
new exporter: multi-page HTML

### ISSUE THREAD

**Issue by nodiscc** [nodiscc/hecat#15]
**PR https://github.com/nodiscc/hecat/pull/66**

**Comment by nodiscc** [comment]
- [ ] If software `github_last_update` (https://github.com/nodiscc/hecat/issues/18) date is older than 6 months, rended the last update date in orange

**Comment by nodiscc** [comment]
- [ ] add all tags to the sidebar

**Comment by nodiscc** [comment]
- [ ] append the number of items next to each tag in the sidebar

**Comment by nodiscc** [comment]
- [ ] Add stars count next to the name https://github.com/awesome-selfhosted/awesome-selfhosted/issues/3019
- [ ] Add last update date next to the name https://github.com/awesome-selfhosted/awesome-selfhosted/issues/3019
- [ ] If last update date is older than 6 months, render the date in orange
